# Generated by Django 2.2.12 on 2020-04-27 22:52

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CloudCompany',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=500)),
            ],
        ),
    ]
