# Generated by Django 2.2.12 on 2020-04-30 04:21

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocloud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(default='KwaCoin', max_length=128)),
                ('image', models.CharField(blank=True, max_length=128, null=True)),
                ('maxSupply', models.DecimalField(decimal_places=2, max_digits=15)),
                ('startDate', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='cloudcompany',
            name='address',
        ),
        migrations.AddField(
            model_name='cloudcompany',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='cloudcompany',
            name='founded',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='cloudcompany',
            name='image',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='cloudcompany',
            name='legitimacy',
            field=models.CharField(choices=[('OK', 'Checked'), ('QS', 'Questionable'), ('BAD', 'Scam')], default='Questionable', max_length=12),
        ),
        migrations.AddField(
            model_name='cloudcompany',
            name='location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cloudcompany',
            name='website',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='cloudcompany',
            name='title',
            field=models.CharField(default='KwaKwa LTD', max_length=128),
        ),
        migrations.CreateModel(
            name='CloudContract',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(default='KwaContract', max_length=128)),
                ('image', models.CharField(blank=True, max_length=128, null=True)),
                ('duration', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('hasRate', models.DecimalField(decimal_places=2, max_digits=15)),
                ('coins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cryptocloud.Coin')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cryptocloud.CloudCompany')),
            ],
        ),
        migrations.AddField(
            model_name='cloudcompany',
            name='coins',
            field=models.ManyToManyField(to='cryptocloud.Coin'),
        ),
    ]
