# Generated by Django 2.2.12 on 2020-05-04 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocloud', '0002_auto_20200429_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='token',
            field=models.CharField(default='KwaToken', max_length=128),
        ),
    ]
