# Generated by Django 2.2.12 on 2020-05-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocloud', '0004_auto_20200506_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='coinGecko',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
