# Generated by Django 2.2.12 on 2020-05-12 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocloud', '0005_auto_20200507_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloudcontract',
            old_name='coins',
            new_name='coin',
        ),
        migrations.RenameField(
            model_name='cloudcontract',
            old_name='hasRate',
            new_name='hashRate',
        ),
        migrations.RemoveField(
            model_name='cloudcompany',
            name='coins',
        ),
        migrations.AlterField(
            model_name='coin',
            name='maxSupply',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
