# Generated by Django 2.2.12 on 2020-05-07 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocloud', '0005_auto_20200507_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='currentSupply',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coin',
            name='maxSupply',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
