# Generated by Django 2.2.12 on 2020-05-13 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocloud', '0006_auto_20200511_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudcontract',
            name='description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
