# Generated by Django 2.2.12 on 2020-05-07 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocloud', '0006_auto_20200507_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='currentSupply',
        ),
    ]
