# Generated by Django 2.2.12 on 2020-07-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocloud', '0009_auto_20200512_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='blockTime',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
