# Generated by Django 2.2.12 on 2020-07-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocloud', '0010_coin_blocktime'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='blockReward',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
